language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: B0eSPpJi8FnqZTpPzR0+VFgoS6fwbIxLz3bDl6GfZb4oW5mUIisl1OT+u7+gRGiwj2ALF2Y06D21fCDXB+tfbqnM3O3ePn0kUWlUa/tmT1U/hdPJ5UaMgoaYsXB6gm1MGUuc9oNNWFHFn+TMGWMpYxY0Fl3mTjAmjjNftCqwgit3imVGSa2NL4VIo0AokaDOJbSud0tjw1tsGxthKFqLPcBKZxewGI+Pxb3NEOqc6P3YgHZTV5DpL7GZTXIyHGumXVUMEu5AFBCD2rNFXMpkjDSWM3eJue09MoEfcz8obdju8k3qj7TIlcWhZF2UL1zdZU/1d71AWfcxqASl1p0cgTljgoo0IYWandDPNI9qUu+XyJrvxy5ZLSiyS2UI4Ael2y1b2Q0oiacnQ+VRtpcJzjvgg0M8l3LQkYRBr7JWwwGUsFVxigXfKdprhCxFhshp9a9U52/ZegmlzoyDbgCBrNzMeSvGm4d9WZmk8pnLctumhGPPUXl6uroMvvPw97rIfKM7T9llBRfujHPi8fpgdwvBgsDVJL1f7ybMxYUwdQID98ZVhde11QzXLzky8Id/OJBfUfosWwPGDskqBdIEgGa50K/F3Tz/btksory7D3NvtjkLxiGa3Z/DftHiloIeFHWRAyGdtgAa8VmsEqF2smyPF8211qyN1Mc76xYxo8k=
  app: guestbook-server
  on:
    repo: codeannie/guestbook-server